CREATE TABLE IF NOT EXISTS service_token (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    token_name VARCHAR(100) NOT NULL,
    token_value VARCHAR(128) NOT NULL UNIQUE,
    token_type VARCHAR(32) NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    expires_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS file_record (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    original_name VARCHAR(255) NOT NULL,
    object_key VARCHAR(512) NOT NULL UNIQUE,
    file_url VARCHAR(1024) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    content_hash VARCHAR(64) NULL UNIQUE,
    file_size BIGINT NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS token_usage_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    token_id BIGINT NOT NULL,
    hub VARCHAR(32) NOT NULL,
    action VARCHAR(32) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_token_id (token_id),
    KEY idx_hub_action (hub, action)
);

CREATE TABLE IF NOT EXISTS short_link (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    code VARCHAR(16) NOT NULL UNIQUE,
    target_url VARCHAR(2048) NOT NULL,
    remark VARCHAR(100) NULL,
    status TINYINT NOT NULL DEFAULT 1,
    expires_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS link_visit_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    link_id BIGINT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_link_created (link_id, created_at)
);
