CREATE TABLE IF NOT EXISTS ip_ban (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ip_address VARCHAR(45) NOT NULL,
    reason VARCHAR(120) NOT NULL,
    banned_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_ip_ban_address (ip_address)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
