CREATE TABLE IF NOT EXISTS site_article (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL COMMENT '文章标题',
    summary VARCHAR(500) COMMENT '文章摘要',
    cover_url VARCHAR(1000) COMMENT '封面图 URL',
    content LONGTEXT NOT NULL COMMENT 'Markdown 正文',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态: 0=草稿/隐藏, 1=已发布',
    view_count INT NOT NULL DEFAULT 0 COMMENT '阅读量',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文章表';
