DROP PROCEDURE IF EXISTS AddColumnIfNotExist;
DELIMITER //
CREATE PROCEDURE AddColumnIfNotExist()
BEGIN
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
    ALTER TABLE site_notification ADD COLUMN source_author VARCHAR(64) AFTER source_id;
END //
DELIMITER ;
CALL AddColumnIfNotExist();
DROP PROCEDURE AddColumnIfNotExist;
